#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/color.sh

echo -e "${GREEN}Showing sublime/VSCode shortcuts commands${NC}\n"

echo -e "\t${BLUE}Description${NC}\t\t\t\t\t${YELLOW}Shortcut${NC}"
echo -e "\t${BLUE}================${NC}\t\t\t\t${YELLOW}================${NC}"

echo -e "\t${BLUE}Cut line${NC}\t\t\t\t\t${YELLOW}Ctrl + X${NC}"
echo -e "\t${BLUE}Insert line after${NC}\t\t\t\t${YELLOW}Ctrl + ↩${NC}"
echo -e "\t${BLUE}Move line/selection up/down${NC}\t\t\t${YELLOW}Ctrl + ⇧ + ↑/↓${NC}"
echo -e "\t${BLUE}Select line - Repeat to select next lines${NC}\t${YELLOW}Ctrl + L${NC}"
echo -e "\t${BLUE}Select word - Repeat select others occurrences${NC}\t${YELLOW}Ctrl + D${NC}"
echo -e "\t${BLUE}Jump to closing/opening parentheses${NC}\t\t${YELLOW}Ctrl + M${NC}"
echo -e "\t${BLUE}Select all contents of the current parentheses${NC}\t${YELLOW}Ctrl + ⇧ + M${NC}"
echo -e "\t${BLUE}Delete Line${NC}\t\t\t\t\t${YELLOW}Ctrl + ⇧ + K${NC}"
echo -e "\t${BLUE}Delete from cursor to end of line${NC}\t\t${YELLOW}Ctrl + KK${NC}"
echo -e "\t${BLUE}Delete from cursor to start of line${NC}\t\t${YELLOW}Ctrl + K + ⌫${NC}"
echo -e "\t${BLUE}Duplicate line(s)${NC}\t\t\t\t${YELLOW}Ctrl + ⇧ + D${NC}"
echo -e "\t${BLUE}Join line below to the end of the current line${NC}\t${YELLOW}Ctrl + J${NC}"
echo -e "\t${BLUE}Comment/un-comment current line${NC}\t\t\t${YELLOW}Ctrl + /${NC}"
echo -e "\t${BLUE}Redo, or repeat last keyboard shortcut command${NC}\t${YELLOW}Ctrl + Y${NC}"
echo -e "\t${BLUE}Quick-open files by name${NC}\t\t\t${YELLOW}Ctrl + P${NC}"
echo -e "\t${BLUE}Goto symbol${NC}\t\t\t\t\t${YELLOW}Ctrl + R${NC}"
echo -e "\t${BLUE}Goto word in current file${NC}\t\t\t${YELLOW}Ctrl + ;${NC}"
echo -e "\t${BLUE}Goto line in current file${NC}\t\t\t${YELLOW}Ctrl + G${NC}"
echo -e "\t${BLUE}Goto Definition${NC}\t\t\t\t\t${YELLOW}Ctrl + Alt + G${NC}"
echo -e "\t${BLUE}Command prompt${NC}\t\t\t\t\t${YELLOW}Ctrl + ⇧ + P${NC}"
echo -e "\t${BLUE}Find${NC}\t\t\t\t\t\t${YELLOW}Ctrl + F${NC}"
echo -e "\t${BLUE}Replace${NC}\t\t\t\t\t\t${YELLOW}Ctrl + H${NC}"
echo -e "\t${BLUE}Find in files${NC}\t\t\t\t\t${YELLOW}Ctrl + ⇧ + F${NC}"
echo -e "\t${BLUE}Switch to tab number [NUM]${NC}\t\t\t${YELLOW}Alt + [NUM]${NC}"
echo -e "\t${BLUE}Revert view to single column${NC}\t\t\t${YELLOW}Alt + ⇧ + 1 ${NC}"
echo -e "\t${BLUE}Split view into two columns${NC}\t\t\t${YELLOW}Alt + ⇧ + 2 ${NC}"
echo -e "\t${BLUE}Transform to Uppercase${NC}\t\t\t\t${YELLOW}Ctrl + KU${NC}"
echo -e "\t${BLUE}Transform to Lowercase${NC}\t\t\t\t${YELLOW}Ctrl + KL${NC}"
echo -e "\t${BLUE}Git blame show all${NC}\t\t\t\t${YELLOW}Ctrl + Shift + Alt + b${NC}"
echo -e "\t${BLUE}Git blame erase all${NC}\t\t\t\t${YELLOW}Ctrl + Shift + Alt + e${NC}"
